export { Home } from './Home';
export { Instituto } from './Instituto';
export { OfertaEducativa } from './OfertaEducativa';
export { Recursos } from './Recursos';
export { FAQ } from './FAQ';
export { Contacto } from './Contacto';
export { Login } from './Login';
export { LoginDocentes } from './LoginDocentes';
export { Docentes } from './Docentes';
export { default as Coordinador } from './Coordinador';
export { AvisoPrivacidad } from './AvisoPrivacidad';
export { AdminUsuarios } from './AdminUsuarios';
export { default as JefeMetrics } from './JefeMetrics';
export { default as DirectorMetrics } from './DirectorMetrics';
export { default as Contador } from './Contador';
export { default as Asesor } from './Asesor';
